language: python
python: "3.5"

install: "pip install pypandoc"

deploy:
  provider: pypi
  user: 
    secure: "cb36W8INvyLZfAUQiB6eomL/anZfOqonkmmvLvtacPfZ++wjYuqLg1lNor5n15WuLCsjfYrlZLxGq3a6IpFlkkf3L8AW+X59J9sjdRCm5aSgBv0IkvqX1jk4gKBFaf6KSnCTX0rBGPJTWTfk8NSCnxS3OJl0HiqjIjQhLBrQXtHG0uxrefxh1+K/3xNiRXLiSQ+pISSDOizc07rRJ200XHaYmD+Nno/vmobzHxD79xcnPiv6/WWxMgqsggyK8ePea7I58nT90T/5a9UdwrAfPKPH/Bg5DRqAmQEUFf3Z+NmtIqRb20gf9uxQnKnvoqlsixnCfcrk/pgzyChp0AjYYgsbSsDrDNpOBoHoU1TMAmD8HyYiHzSZjBMkZTEdXO9sxpXvbYLpfP7mJm4bbX0mRD82dAX6UOnQ14iYCsRAZZhDEAHznq4pM6YyATNHrQsQdMEQNIXOs0iljbXWrYjgoNruWpDptQhJAA/dqMI6+PCPyZscOKmGtvOodam7MGo3g94AIL/el+zK6P0pLH285SwcGZbosRO8Y6qJ/5VEEtmClkO9+NEXEx0TCsDrfqxXjVVPHwd9bfTpgk9x5XK8vg0Ob0B/iJzHpLOkodSq9430M2EdAotwurizNvNZeWjEYwzxNNquv4EwV3CxihCwtbf8hpzbMdXWxclm9hNbqQ0="
  password: 
    secure: "m8myBHu/Pia0EyuZVqBhFYm38rtW4DNoK5QqOvEVXOjWrs4YqyZ4oufi9ssdC8XYdh8WOfErha22VIQogr8SAtd7zwjHZBnX04YBv0k81tf2p7AJ9/NLJ2AnI0FDXwKZ6uYRXsde4LZT+jJ7JkhTC6uH0/XFbVffRXaeFBsf+s6LPdluoaPDBDqkiiqZnRz2Ozut5lRkXIQTE8GrfnJkZYOdrWJwhIIhGmDhCbTQkttUxM7KFEvB1POdoGo8IYTo7JXtLw8EgHN2Nfcqm9pqa2fnj3oLDTW3ZoPd1hhvRpuosj0wDjWPiLkfnuvSK///7w6SOk/uklPZNvxzPlnyIJsCwjQB4wOzVvhxjaM9AZVpyka2zB3pUWEoc1u9ZNaK3BjPXxvMFznlZbcP4/1TmQm2fbJAZsks5glTJZT4yT5PGYGfZZkY+32jrQHOr8bKZYqYR0yGQhhFiYYk3IeexxViEkqFzQ165pcgbKvXR2CO8h2lwXDlAPLdLmHiFR+HR5avnYHC+fDFeI7N6uB2XzOsLRo03Z2Ix1hDgKLNmtG/xKPu8axvrAxPlIMMUbTGVaYkyK/kkYt1//AwhtK1zw+ZH8San0+Rh/M1ZXr0M4JNBQEJCt0WL/DBVQQ8VBoDQgE1l/79Em3iGg6msDDB/C/svgEhFyZEu+C7Y9Rp4Ss="
  on:
    branch: master